# Application de metallb: las IPs de tipo LoadBalancer.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/rh-workshop/workshop-platform.git
    targetRevision: main
    path: metallb/gitops/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
