apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: shared-gateway-default
  namespace: platform-gateway
spec:
  defaults:
    rules:
      authentication:
        token-valido:
          jwt:
            # Dominio del cluster de laboratorio: al cambiar de cluster hay que actualizarlo aqui.
            issuerUrl: https://sso.apps.cluster-qthlq.dyn.redhatworkshops.io/realms/workshop
