apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: gateway-hostname.yaml
    target:
      kind: Gateway
      name: shared-gateway
  - path: authpolicy-default-issuer.yaml
    target:
      kind: AuthPolicy
      name: shared-gateway-default
