# En dev el host compartido de APIs apunta al dominio de apps del cluster de desarrollo.
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: shared-gateway-apis
  namespace: platform-gateway
spec:
  # Sustituir por el dominio del cluster de DESARROLLO: apis.apps.<cluster-dev>.<dominio-base>
  host: apis.apps.ocp.lplb4.sandbox3335.opentlc.com
