apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: install-operators-workload-binding
  namespace: open-cluster-management
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: clusters-workload
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: install-operators-workload
