# Application de acm (solo hub): el hub de gobierno y las politicas.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm
  namespace: openshift-gitops
spec:
  project: workshop-platform
  source:
    repoURL: https://github.com/rh-workshop/workshop-demo-platform.git
    targetRevision: main
    path: acm/gitops/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: open-cluster-management
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
