# Gobierno del namespace de negocio del cluster de contingencia.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/namespaces/workshop-demo-contingencia
labels:
  - pairs:
      app.kubernetes.io/part-of: workshop-platform
      workshop.redhat.com/environment: contingencia
