# Namespace de aplicación sin desviaciones: perfil app-namespace completo.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workshop-demo-test
resources:
  - ../../profiles/app-namespace
