apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: shared-gateway-default
  namespace: platform-gateway
spec:
  defaults:
    rules:
      authentication:
        token-valido:
          jwt:
            issuerUrl: https://sso.apps.cluster-lrr82.dyn.redhatworkshops.io/realms/workshop
