apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - appproject.yaml
  - hub/acm-application.yaml
  - hub/quay-application.yaml
  - hub/acs-application.yaml
  - hub/monitoring-application.yaml
  - hub/pipelines-application.yaml
  - hub/developer-hub-application.yaml
  - ../clusters
  - ../appsets
