# Une la Policy de operadores del hub con su Placement.
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: install-operators-hub-binding
  namespace: open-cluster-management
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: operadores-hub
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: install-operators-hub
