apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap-kafka-metrics.yaml
  - kafka-podmonitor.yaml
  - kafkanodepool-controller.yaml
  - kafkanodepool-broker.yaml
  - kafka.yaml
  - kafkatopic-demo-events.yaml
  - kafkatopic-demo-events-dlq.yaml
  - kafkauser-demo-producer.yaml
  - kafkauser-demo-consumer.yaml
