apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - namespace-gateway.yaml
  - kuadrant.yaml
  - gateway.yaml
  - shared-gateway-tlspolicy.yaml
  - shared-gateway-default-authpolicy.yaml
