apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - managedclustersetbinding.yaml
  - placements/placement-clusters-all.yaml
  - placements/placement-clusters-dev.yaml
  - placements/placement-clusters-test.yaml
  - placements/placement-clusters-prod.yaml
  - placements/placement-clusters-contingencia.yaml
  - gitopscluster.yaml
