# Selecciona los clusters de rol desarrollo (environment=dev).
# Hace que los overlays "dev" de los productos workload caigan en los spokes etiquetados environment=dev, no en el hub.
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: clusters-dev
  namespace: openshift-gitops
spec:
  clusterSets:
  - default
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          environment: dev
