apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: configmap-prometheus-retention.yaml
    target:
      kind: ConfigMap
      name: cluster-monitoring-config
