# Ajustes de PRODUCCION de Keycloak: HA (2 instancias), hostname del cluster prod
# y hostname strict (evita host spoofing sobre URLs de tokens/redirects).
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 2
  hostname:
    hostname: sso.apps.cluster-lrr82.dyn.redhatworkshops.io
    strict: true
    strictBackchannel: true
