apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - ../../base
  - keycloak-pdb.yaml
patches:
  - path: keycloak-prod.yaml
  - target:
      kind: Route
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/host
        value: sso.apps.cluster-lrr82.dyn.redhatworkshops.io
labels:
  - pairs:
      app.kubernetes.io/part-of: workshop-platform
      workshop.redhat.com/environment: prod
